### PR TITLE
Modernize dasynq

### PR DESCRIPTION
**Pull request by concatime**
Hi Davin.

This PR tries to standardize and modernize the library by using Meson, CI and clang-tidy.
The examples are working too with Meson.
Makefiles are working in my system for checking and installing dasynq.

- [x] move headers in `include` and `include/dasynq`
- [x] fixed include guars
- [x] use modern c++ headers
- [ ] add documentation about Meson build
- [x] test CI builds

Waiting for your feedback :)

### CODE REVIEW

**Comment by davmac314** [comment]
Hmm, this is a bit more than we discussed via email... I don't want the header files renamed to .hpp, this is an API break and not a style I particularly like. It is not the case that ".hpp" is the correct extension for C++ headers; that is just a convention that is used in some projects.

The convention (particularly in documentation) should still be `#include "dasynq."` rather than `#include <dasynq.h>`. The latter only works if dasynq.h is in a system header path (which the default "make install" now ensures, true, but it's not universal).

I'm guess I'm ok with changing the inclusion of C headers (eg `<signal.h>`) to the C++ style (`<csignal>`), though the reason I had used the former was because POSIX header is specified to have certain functions that were being used, which are not part of the C++ standard. It's not a big deal though because in practice, the C++ header just pulls in the equivalent system (POSIX) header.

I'm a little uneasy about adding CI for sourcehut, which I don't use, but I guess it's ok. However, could you maybe add a README in the `.builds` directory explaining what it is for?

The end-of-namespace comment changes are ok.

Note that I may refuse any other small changes that I consider to be "bike-shedding" - I don't like unnecessary churn in the code and in the history, so if you want to make any other changes you might want to check with me first. Thanks!

**Comment by davmac314** [comment]
ping! - are you happy to accept the feedback given? I hope you understand why I don't want to accept all the changes currently in the pull request. I do see value in the other changes however (as discussed in comment above).

I want to make some changes to Dasynq soon, but if you do plan to re-work this PR to satisfy my requests above then I can give you some time to do that first. Since it's a structural change I think it would create more difficulty for you if I make other changes now. So, just wanted to check if you will re-work this PR? Thanks.

**Comment by concatime** [comment]
Understood. Yes, I’m dtill planning to accept your feedback. Should be done by the end of the day :)

**Comment by concatime** [comment]
The build was successful in [Archlinux](https://builds.sr.ht/~iemaghni/job/379349), but not on [Alpine](https://builds.sr.ht/~iemaghni/job/379348).
```
cat log.txt | grep error
../dasynq/include/dasynq/timerbase.h:401:65: error: 'timeval' has not been declared
../dasynq/include/dasynq/timerbase.h:401:78: error: 'timeval' has not been declared
../dasynq/include/dasynq/timerbase.h:443:57: error: 'timeval' has not been declared
../dasynq/include/dasynq/timerbase.h:443:70: error: 'timeval' has not been declared
../dasynq/include/dasynq/timerbase.h:414:20: error: request for member 'tv_sec' in 'tv', which is of non-class type 'int'
../dasynq/include/dasynq/timerbase.h:415:20: error: request for member 'tv_usec' in 'tv', which is of non-class type 'int'
```

**Comment by concatime** [comment]
I will replace `<time.h>`/`<ctime>` by `<sys/time.h>`, [which defines `timeval`](https://pubs.opengroup.org/onlinepubs/7908799/xsh/systime.h.html).

**Comment by concatime** [comment]
```
../dasynq/include/dasynq/timerbase.h:401:65: error: 'timeval' has not been declared
  401 |     inline void process_timers(clock_type clock, bool &do_wait, timeval &tv, timeval *&wait_tv)
      |                                                                 ^~~~~~~
../dasynq/include/dasynq/timerbase.h:401:78: error: 'timeval' has not been declared
  401 |     inline void process_timers(clock_type clock, bool &do_wait, timeval &tv, timeval *&wait_tv)
      |                                                                              ^~~~~~~
../dasynq/include/dasynq/timerbase.h:443:57: error: 'timeval' has not been declared
  443 |     inline void process_monotonic_timers(bool &do_wait, timeval &tv, timeval *&wait_tv)
      |                                                         ^~~~~~~
../dasynq/include/dasynq/timerbase.h:443:70: error: 'timeval' has not been declared
  443 |     inline void process_monotonic_timers(bool &do_wait, timeval &tv, timeval *&wait_tv)
      |                                                                      ^~~~~~~
```
Also, shouldn’t we prepand `timeval` by `struct`?

**Comment by concatime** [comment]
Last thing, for `timespec`, we could do this:
```cpp
#include <ctime>

#if __cplusplus < 201703UL
namespace std {
using ::timespec;
}
#endif
```
and use `std::timespec` as mentionned [here](https://en.cppreference.com/w/cpp/chrono/c/timespec).

**Comment by concatime** [comment]
In any case, the build right now is successful in both [Arch Linux](https://builds.sr.ht/~iemaghni/job/379381) and [Alpine Linux](https://builds.sr.ht/~iemaghni/job/379382).

**Comment by concatime** [comment]
Don’t merge yet, I’m fixing the build on FreeBSD.

**Comment by concatime** [comment]
Successful builds:
  - FreeBSD 11.x: https://builds.sr.ht/~iemaghni/job/379413
  - FreeBSD 12.x: https://builds.sr.ht/~iemaghni/job/379411
  - OpenBSD 6.8: https://builds.sr.ht/~iemaghni/job/379414

**Comment by davmac314** [comment]
> I will replace in `timberbase.h` `<time.h>`/`<ctime>` by `<sys/time.h>`, [which defines `struct timeval`](https://pubs.opengroup.org/onlinepubs/7908799/xsh/systime.h.html), okay?
> 
> EDIT: Nop, can’t do. `<time.h>`/`<ctime>` are required for `struct timespec`. I will just add `<sys/time.h>` then, instead of replacing.

Yes, we need both! :+1: 

> Also, shouldn’t we prepend `timeval` by `struct`?

No, this is C++, it's not needed.



> Last thing, for `timespec`, we could do this:
> 
> ```c++
> #include <ctime>
> 
> #if __cplusplus < 201703UL
> namespace std {
> using ::timespec;
> }
> #endif
> ```
> 
> and use `std::timespec` as mentionned [here](https://en.cppreference.com/w/cpp/chrono/c/timespec).

No! We don't want to be injecting anything into the `std` namespace. Just refer to it as `timespec` which is the same thing as `std::timespec` anyway.

**Comment by davmac314** [comment]
So looking at it thoroughly I see the following outstanding issues:

- `.build` directory still needs a README or comment in one of the files explaining what they are for ("this is for sourcehut CI")
- remove `struct` which has been added at front of `struct timeval`
- the "Description:" field of the generated pkg-config (*.pc) file should be the same regardless of whether it's a makefile build or meson build. I'd be happy for you to update the makefile build to match what you've put for the meson build (or the other way around if you prefer).

The rest looks fine. If you can make these changes I will merge. Thanks!

**Comment by concatime** [comment]
Should be bone today.

**Comment by concatime** [comment]
Done, sorry for the late response. One last thing, in pkgconfig, is the name `dasynq` or `Dasynq`?

**Comment by davmac314** [comment]
> Done, sorry for the late response. One last thing, in pkgconfig, is the name `dasynq` or `Dasynq`? Because, if the name is `Dasynq`, the file should be named `Dasynq.pc`. In your makefile, you set to name to `Dasynq`, but the file is `dasynq.pc`. In Meson, I have `Name: dasynq` and `dasynq.pc`.

The "Name:" specifies a human-readable name. It is supposed to be Dasynq. The filename should be dasynq.pc. They don't need to match exactly.

**Comment by concatime** [comment]
Done.

**Pull request merged**
